<?php
    // 201
    $ip_201 = '200.89.175.51';
    $user_201 = 'VRA_92128160102772@int.fibercorp.com.ar';
    $Pass_201 = '';

    // 202
    $ip_202 = '200.73.131.25';
    
    // 203 
    $ip_203 = '20.127.209.22';
    $user_203 = 'cleversoft';
    $Pass_203 = '*.kvy2012*.22';

    // 302 
    $ip_302 = '201.253.99.24';
    $user_302 = 'user';
    $Pass_302 = '*.kvy2024*.';

    // Dobby
    $ip_Dobby = '192.168.1.95';
    $user_Dobby = 'admin';
    $Pass_Dobby = 'teset2023*.';
?>